[slurm_system]
log_folder = "/scratch/kmitsuzawa/project/agentic-ai-pipeline-analysis/exec_a781a9526be07ed1cd1b8044c7ffb94bcc1895b6"

default_profiles = ["amd6000", "v100"]

is_delete_worker_output = true
is_download_resources_prepost = true
is_download_resources_at_worker = false
max_io_workers = 1
io_queue_size = 2


[slurm_system.profiles.amd6000]
    partition = "amd6000"
    time = "10:00:00"
    n_nodes_budget = 1
    n_tasks_per_node = 1
    n_cpus_per_task = 1
    n_gpus_per_task = 1
    gres = "gpu:2"

[slurm_system.profiles.intelv100]
    partition = "intelv100"
    time = "10:00:00"
    n_nodes_budget = 1
    n_tasks_per_node = 1
    n_cpus_per_task = 1
    n_gpus_per_task = 1
    gres = "gpu:2"


[local_server]
model_id = "Qwen/Qwen2.5-7B"
port = 8000

[local_server.quantization_config_dict]
load_in_4bit = false
load_in_8bit = true