[submitit_system]
log_folder = "pipeline_outcomes_hf_local"
default_profiles = ["local"]
is_delete_worker_output = true
is_download_resources_prepost = true
is_download_resources_at_worker = false
max_io_workers = 1
io_queue_size = 2

[submitit_system.profiles.local]
partition = "dev"
time = "03:00:00"
n_nodes_budget = 1
n_tasks_per_node = 1
n_cpus_per_task = 1
n_gpus_per_task = 1
gres = "gpu:1"

[llm_client]
openai_api_base = "http://localhost:8000/v1/"
model = "default"

[llm_generation_params]
temperature = 0.1
max_tokens = 999
top_p = 0.9
presence_penalty = 0.0
frequency_penalty = 0.0
stop = []
